package druide.hibernate.pojo;
// Generated 9 dec. 2013 16:31:43 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Integer position;
     private Set<Rang> rangs = new HashSet<Rang>(0);

    public Permission() {
    }

    public Permission(String nom) {
        this.nom = nom;
    }
    public Permission(String nom, Integer position, Set<Rang> rangs) {
       this.nom = nom;
       this.position = position;
       this.rangs = rangs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }
    
    public Set<Rang> getRangs() {
        return this.rangs;
    }
    
    public void setRangs(Set<Rang> roles) {
        this.rangs = roles;
    }




}


